version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.openjfx:javafx-controls
    versions:
    - "> 11.0.2"
  - dependency-name: org.openjfx:javafx-fxml
    versions:
    - "> 11.0.2"
  - dependency-name: org.openjfx:javafx-media
    versions:
    - "> 11.0.2"
  - dependency-name: org.openjfx:javafx-swing
    versions:
    - "> 11.0.2"
  - dependency-name: guru.nidi:graphviz-java
    versions:
    - 0.18.0
